### PR TITLE
Update workflow.yml

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by lefessan** [comment]
Thanks for your PR, I have already updated the file (see the other PR that has changed from its original intent...), it might be easier to compare once the other PR has been merged.

**Comment by lefessan** [comment]
By the way, I don't think the cache key should contain a hash of the `.drom` file : `drom` can be used as a scafolder, creating only the initial files. In such a case, the user would edit the `dune-project` file to regenerate the opam files, without using `drom` anymore, so the `.drom` would be inconsistent with the state of the `.opam` files. In the other PR, I use a hash of the `.opam` files only.

**Comment by lefessan** [comment]
I modified `src/github.ml` to generate a workflow with your modifications, I think it should be mostly similar now. Thanks !

**Comment by smorimoto** [comment]
I just read your comment because I was sick and away from here for a while. That looks good!

**Pull request closed without merging**
